services:
    wordpress:
        container_name: wordpress
        image: wordpress:php8.2-apache
        restart: always
        env_file: .env
        stdin_open: true
        tty: true
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: $MYSQL_USER
            WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
            WORDPRESS_DB_NAME: wordpress
        volumes:
            - wordpress_data:/var/www/html

    db:
        container_name: db
        image: mariadb:11.2
        restart: always
        env_file: .env
        environment:
            MYSQL_DATABASE: wordpress
        volumes:
            - mariadb_data:/var/lib/mysql

    adminer:
        container_name: adminer
        image: adminer:4.8.1
        restart: unless-stopped
        ports:
        - 8080:8080

    nginx:
        container_name: nginx
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
            - /etc/letsencrypt:/etc/nginx/ssl
            - ./webroot:/var/www/html

volumes:
    mariadb_data:
    wordpress_data:
